module(name = "com_github_buildbarn_bb_remote_asset")

bazel_dep(name = "aspect_bazel_lib", version = "2.22.5")
bazel_dep(name = "bazel_remote_apis")
bazel_dep(name = "cel-spec", version = "0.25.3")
bazel_dep(name = "com_github_buildbarn_bb_storage")
bazel_dep(name = "gazelle", version = "0.51.3")
bazel_dep(name = "googleapis", version = "0.0.0-20260929-28769825")
bazel_dep(name = "jsonnet_go", version = "0.22.0")
bazel_dep(name = "protobuf", version = "35.1")
bazel_dep(name = "protoc-gen-validate", version = "1.3.3")
bazel_dep(name = "rules_go", version = "0.63.0")
bazel_dep(name = "rules_jsonnet", version = "0.7.2")
bazel_dep(name = "toolchains_llvm", version = "1.8.0")

# Use `archive_override` instead of `git_override` to avoid depending on local
# git, and make it fetchable by the remote downloader.
archive_override(
    module_name = "bazel_remote_apis",
    integrity = "sha256-XAEBIXXuK5uv9yVvarYDBSWiPFpRAbNTAF+qf+HcuV0=",
    # https://github.com/bazelbuild/remote-apis/pull/378
    patches = ["//:patches/bazel_remote_apis/upstream-pr-378.diff"],
    strip_prefix = "remote-apis-adbf4a27c86fbea4a37637a6cbcacef372406fe7",
    urls = ["https://github.com/bazelbuild/remote-apis/archive/adbf4a27c86fbea4a37637a6cbcacef372406fe7.tar.gz"],
)

archive_override(
    module_name = "com_github_buildbarn_bb_storage",
    integrity = "sha256-ULS5Z21flQ5nW03e9jb2+yFO1PqVFa0m9qA2cCFYVd8=",
    patches = [
        "//:patches/com_buildbarn_bb_storage/workflows.diff",
    ],
    strip_prefix = "bb-storage-027bd797f1ec7631b49c4f459c06dee995f7e2f9",
    urls = ["https://github.com/buildbarn/bb-storage/archive/027bd797f1ec7631b49c4f459c06dee995f7e2f9.tar.gz"],
)

single_version_override(
    module_name = "gazelle",
    patches = ["//:patches/gazelle/dont-flatten-srcs.diff"],
)

single_version_override(
    module_name = "toolchains_llvm",
    patches = ["//:patches/toolchains_llvm/non-root.diff"],
)

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.from_file(go_mod = "//:go.mod")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
use_repo(
    go_deps,
    "com_github_bazelbuild_remote_apis",
    "com_github_golang_mock",
    "com_github_prometheus_client_golang",
    "com_github_stretchr_testify",
    "org_golang_google_genproto_googleapis_rpc",
    "org_golang_google_grpc",
    "org_golang_google_protobuf",
    "org_golang_x_lint",
)

go_deps_dev = use_extension("@gazelle//:extensions.bzl", "go_deps", dev_dependency = True)
go_deps_dev.gazelle_override(
    build_file_generation = "on",
    path = "github.com/cncf/xds/go",
)
go_deps_dev.module_override(
    patches = ["@com_github_buildbarn_bb_storage//:patches/com_github_grpc_ecosystem_go_grpc_prometheus/client-metrics-prevent-handled-twice.diff"],
    path = "github.com/grpc-ecosystem/go-grpc-prometheus",
)
go_deps_dev.module_override(
    patches = ["@com_github_buildbarn_bb_storage//:patches/org_golang_google_genproto_googleapis_bytestream/service-registrar.diff"],
    path = "google.golang.org/genproto/googleapis/bytestream",
)
go_deps_dev.module_override(
    patches = ["@com_github_buildbarn_bb_storage//:patches/org_golang_x_lint/generic.diff"],
    path = "golang.org/x/lint",
)
go_deps_dev.module_override(
    patches = ["@com_github_buildbarn_bb_storage//:patches/org_golang_x_oauth2/injectable-clock.diff"],
    path = "golang.org/x/oauth2",
)
go_deps_dev.module_override(
    patches = ["@com_github_buildbarn_bb_storage//:patches/org_golang_x_sys/o-search.diff"],
    path = "golang.org/x/sys",
)
go_deps_dev.module_override(
    patches = [
        "@com_github_buildbarn_bb_storage//:patches/org_uber_go_mock/generics.diff",
        "@com_github_buildbarn_bb_storage//:patches/org_uber_go_mock/mocks-for-funcs.diff",
    ],
    path = "go.uber.org/mock",
)

llvm_dev = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm", dev_dependency = True)
llvm_dev.toolchain(
    llvm_version = "17.0.6",
)
