// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: github.com/buildbarn/bb-remote-asset/pkg/proto/configuration/bb_remote_asset/bb_remote_asset.proto

package bb_remote_asset

import (
	fetch "github.com/buildbarn/bb-remote-asset/pkg/proto/configuration/bb_remote_asset/fetch"
	auth "github.com/buildbarn/bb-storage/pkg/proto/configuration/auth"
	blobstore "github.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                     protoimpl.MessageState             `protogen:"open.v1"`
	GrpcServers               []*grpc.ServerConfiguration        `protobuf:"bytes,3,rep,name=grpc_servers,json=grpcServers,proto3" json:"grpc_servers,omitempty"`
	ContentAddressableStorage *blobstore.BlobAccessConfiguration `protobuf:"bytes,4,opt,name=content_addressable_storage,json=contentAddressableStorage,proto3" json:"content_addressable_storage,omitempty"`
	MaximumMessageSizeBytes   int64                              `protobuf:"varint,5,opt,name=maximum_message_size_bytes,json=maximumMessageSizeBytes,proto3" json:"maximum_message_size_bytes,omitempty"`
	Global                    *global.Configuration              `protobuf:"bytes,6,opt,name=global,proto3" json:"global,omitempty"`
	AllowUpdatesForInstances  []string                           `protobuf:"bytes,7,rep,name=allow_updates_for_instances,json=allowUpdatesForInstances,proto3" json:"allow_updates_for_instances,omitempty"`
	Fetcher                   *fetch.FetcherConfiguration        `protobuf:"bytes,8,opt,name=fetcher,proto3" json:"fetcher,omitempty"`
	AssetCache                *AssetCacheConfiguration           `protobuf:"bytes,9,opt,name=asset_cache,json=assetCache,proto3" json:"asset_cache,omitempty"`
	FetchAuthorizer           *auth.AuthorizerConfiguration      `protobuf:"bytes,10,opt,name=fetch_authorizer,json=fetchAuthorizer,proto3" json:"fetch_authorizer,omitempty"`
	PushAuthorizer            *auth.AuthorizerConfiguration      `protobuf:"bytes,11,opt,name=push_authorizer,json=pushAuthorizer,proto3" json:"push_authorizer,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGrpcServers() []*grpc.ServerConfiguration {
	if x != nil {
		return x.GrpcServers
	}
	return nil
}

func (x *ApplicationConfiguration) GetContentAddressableStorage() *blobstore.BlobAccessConfiguration {
	if x != nil {
		return x.ContentAddressableStorage
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumMessageSizeBytes() int64 {
	if x != nil {
		return x.MaximumMessageSizeBytes
	}
	return 0
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetAllowUpdatesForInstances() []string {
	if x != nil {
		return x.AllowUpdatesForInstances
	}
	return nil
}

func (x *ApplicationConfiguration) GetFetcher() *fetch.FetcherConfiguration {
	if x != nil {
		return x.Fetcher
	}
	return nil
}

func (x *ApplicationConfiguration) GetAssetCache() *AssetCacheConfiguration {
	if x != nil {
		return x.AssetCache
	}
	return nil
}

func (x *ApplicationConfiguration) GetFetchAuthorizer() *auth.AuthorizerConfiguration {
	if x != nil {
		return x.FetchAuthorizer
	}
	return nil
}

func (x *ApplicationConfiguration) GetPushAuthorizer() *auth.AuthorizerConfiguration {
	if x != nil {
		return x.PushAuthorizer
	}
	return nil
}

type AssetCacheConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Backend:
	//
	//	*AssetCacheConfiguration_BlobAccess
	//	*AssetCacheConfiguration_ActionCache
	Backend       isAssetCacheConfiguration_Backend `protobuf_oneof:"backend"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetCacheConfiguration) Reset() {
	*x = AssetCacheConfiguration{}
	mi := &file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetCacheConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetCacheConfiguration) ProtoMessage() {}

func (x *AssetCacheConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetCacheConfiguration.ProtoReflect.Descriptor instead.
func (*AssetCacheConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDescGZIP(), []int{1}
}

func (x *AssetCacheConfiguration) GetBackend() isAssetCacheConfiguration_Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *AssetCacheConfiguration) GetBlobAccess() *blobstore.BlobAccessConfiguration {
	if x != nil {
		if x, ok := x.Backend.(*AssetCacheConfiguration_BlobAccess); ok {
			return x.BlobAccess
		}
	}
	return nil
}

func (x *AssetCacheConfiguration) GetActionCache() *blobstore.BlobAccessConfiguration {
	if x != nil {
		if x, ok := x.Backend.(*AssetCacheConfiguration_ActionCache); ok {
			return x.ActionCache
		}
	}
	return nil
}

type isAssetCacheConfiguration_Backend interface {
	isAssetCacheConfiguration_Backend()
}

type AssetCacheConfiguration_BlobAccess struct {
	BlobAccess *blobstore.BlobAccessConfiguration `protobuf:"bytes,1,opt,name=blob_access,json=blobAccess,proto3,oneof"`
}

type AssetCacheConfiguration_ActionCache struct {
	ActionCache *blobstore.BlobAccessConfiguration `protobuf:"bytes,2,opt,name=action_cache,json=actionCache,proto3,oneof"`
}

func (*AssetCacheConfiguration_BlobAccess) isAssetCacheConfiguration_Backend() {}

func (*AssetCacheConfiguration_ActionCache) isAssetCacheConfiguration_Backend() {}

var File_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDesc = "" +
	"\n" +
	"bgithub.com/buildbarn/bb-remote-asset/pkg/proto/configuration/bb_remote_asset/bb_remote_asset.proto\x12'buildbarn.configuration.bb_remote_asset\x1a`github.com/buildbarn/bb-remote-asset/pkg/proto/configuration/bb_remote_asset/fetch/fetcher.proto\x1aGgithub.com/buildbarn/bb-storage/pkg/proto/configuration/auth/auth.proto\x1aQgithub.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore/blobstore.proto\x1aKgithub.com/buildbarn/bb-storage/pkg/proto/configuration/global/global.proto\x1aGgithub.com/buildbarn/bb-storage/pkg/proto/configuration/grpc/grpc.proto\"\xbf\x06\n" +
	"\x18ApplicationConfiguration\x12T\n" +
	"\fgrpc_servers\x18\x03 \x03(\v21.buildbarn.configuration.grpc.ServerConfigurationR\vgrpcServers\x12z\n" +
	"\x1bcontent_addressable_storage\x18\x04 \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationR\x19contentAddressableStorage\x12;\n" +
	"\x1amaximum_message_size_bytes\x18\x05 \x01(\x03R\x17maximumMessageSizeBytes\x12E\n" +
	"\x06global\x18\x06 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12=\n" +
	"\x1ballow_updates_for_instances\x18\a \x03(\tR\x18allowUpdatesForInstances\x12]\n" +
	"\afetcher\x18\b \x01(\v2C.buildbarn.configuration.bb_remote_asset.fetch.FetcherConfigurationR\afetcher\x12a\n" +
	"\vasset_cache\x18\t \x01(\v2@.buildbarn.configuration.bb_remote_asset.AssetCacheConfigurationR\n" +
	"assetCache\x12`\n" +
	"\x10fetch_authorizer\x18\n" +
	" \x01(\v25.buildbarn.configuration.auth.AuthorizerConfigurationR\x0ffetchAuthorizer\x12^\n" +
	"\x0fpush_authorizer\x18\v \x01(\v25.buildbarn.configuration.auth.AuthorizerConfigurationR\x0epushAuthorizerJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\"\xe4\x01\n" +
	"\x17AssetCacheConfiguration\x12]\n" +
	"\vblob_access\x18\x01 \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationH\x00R\n" +
	"blobAccess\x12_\n" +
	"\faction_cache\x18\x02 \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationH\x00R\vactionCacheB\t\n" +
	"\abackendBNZLgithub.com/buildbarn/bb-remote-asset/pkg/proto/configuration/bb_remote_assetb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),          // 0: buildbarn.configuration.bb_remote_asset.ApplicationConfiguration
	(*AssetCacheConfiguration)(nil),           // 1: buildbarn.configuration.bb_remote_asset.AssetCacheConfiguration
	(*grpc.ServerConfiguration)(nil),          // 2: buildbarn.configuration.grpc.ServerConfiguration
	(*blobstore.BlobAccessConfiguration)(nil), // 3: buildbarn.configuration.blobstore.BlobAccessConfiguration
	(*global.Configuration)(nil),              // 4: buildbarn.configuration.global.Configuration
	(*fetch.FetcherConfiguration)(nil),        // 5: buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration
	(*auth.AuthorizerConfiguration)(nil),      // 6: buildbarn.configuration.auth.AuthorizerConfiguration
}
var file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_depIdxs = []int32{
	2, // 0: buildbarn.configuration.bb_remote_asset.ApplicationConfiguration.grpc_servers:type_name -> buildbarn.configuration.grpc.ServerConfiguration
	3, // 1: buildbarn.configuration.bb_remote_asset.ApplicationConfiguration.content_addressable_storage:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	4, // 2: buildbarn.configuration.bb_remote_asset.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	5, // 3: buildbarn.configuration.bb_remote_asset.ApplicationConfiguration.fetcher:type_name -> buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration
	1, // 4: buildbarn.configuration.bb_remote_asset.ApplicationConfiguration.asset_cache:type_name -> buildbarn.configuration.bb_remote_asset.AssetCacheConfiguration
	6, // 5: buildbarn.configuration.bb_remote_asset.ApplicationConfiguration.fetch_authorizer:type_name -> buildbarn.configuration.auth.AuthorizerConfiguration
	6, // 6: buildbarn.configuration.bb_remote_asset.ApplicationConfiguration.push_authorizer:type_name -> buildbarn.configuration.auth.AuthorizerConfiguration
	3, // 7: buildbarn.configuration.bb_remote_asset.AssetCacheConfiguration.blob_access:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	3, // 8: buildbarn.configuration.bb_remote_asset.AssetCacheConfiguration.action_cache:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_init()
}
func file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_init() {
	if File_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto != nil {
		return
	}
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_msgTypes[1].OneofWrappers = []any{
		(*AssetCacheConfiguration_BlobAccess)(nil),
		(*AssetCacheConfiguration_ActionCache)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto = out.File
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_bb_remote_asset_proto_depIdxs = nil
}
