// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: github.com/buildbarn/bb-remote-asset/pkg/proto/configuration/bb_remote_asset/fetch/fetcher.proto

package fetch

import (
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	client "github.com/buildbarn/bb-storage/pkg/proto/configuration/http/client"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetcherConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Backend:
	//
	//	*FetcherConfiguration_Http
	//	*FetcherConfiguration_Error
	//	*FetcherConfiguration_RemoteExecution
	Backend       isFetcherConfiguration_Backend `protobuf_oneof:"backend"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetcherConfiguration) Reset() {
	*x = FetcherConfiguration{}
	mi := &file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetcherConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetcherConfiguration) ProtoMessage() {}

func (x *FetcherConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetcherConfiguration.ProtoReflect.Descriptor instead.
func (*FetcherConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDescGZIP(), []int{0}
}

func (x *FetcherConfiguration) GetBackend() isFetcherConfiguration_Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *FetcherConfiguration) GetHttp() *FetcherConfiguration_HttpFetcherConfiguration {
	if x != nil {
		if x, ok := x.Backend.(*FetcherConfiguration_Http); ok {
			return x.Http
		}
	}
	return nil
}

func (x *FetcherConfiguration) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Backend.(*FetcherConfiguration_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *FetcherConfiguration) GetRemoteExecution() *FetcherConfiguration_RemoteExecutionFetcherConfiguration {
	if x != nil {
		if x, ok := x.Backend.(*FetcherConfiguration_RemoteExecution); ok {
			return x.RemoteExecution
		}
	}
	return nil
}

type isFetcherConfiguration_Backend interface {
	isFetcherConfiguration_Backend()
}

type FetcherConfiguration_Http struct {
	Http *FetcherConfiguration_HttpFetcherConfiguration `protobuf:"bytes,2,opt,name=http,proto3,oneof"`
}

type FetcherConfiguration_Error struct {
	Error *status.Status `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type FetcherConfiguration_RemoteExecution struct {
	RemoteExecution *FetcherConfiguration_RemoteExecutionFetcherConfiguration `protobuf:"bytes,4,opt,name=remote_execution,json=remoteExecution,proto3,oneof"`
}

func (*FetcherConfiguration_Http) isFetcherConfiguration_Backend() {}

func (*FetcherConfiguration_Error) isFetcherConfiguration_Backend() {}

func (*FetcherConfiguration_RemoteExecution) isFetcherConfiguration_Backend() {}

type FetcherConfiguration_HttpFetcherConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *client.Configuration  `protobuf:"bytes,3,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetcherConfiguration_HttpFetcherConfiguration) Reset() {
	*x = FetcherConfiguration_HttpFetcherConfiguration{}
	mi := &file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetcherConfiguration_HttpFetcherConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetcherConfiguration_HttpFetcherConfiguration) ProtoMessage() {}

func (x *FetcherConfiguration_HttpFetcherConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetcherConfiguration_HttpFetcherConfiguration.ProtoReflect.Descriptor instead.
func (*FetcherConfiguration_HttpFetcherConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FetcherConfiguration_HttpFetcherConfiguration) GetClient() *client.Configuration {
	if x != nil {
		return x.Client
	}
	return nil
}

type FetcherConfiguration_RemoteExecutionFetcherConfiguration struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	ExecutionClient *grpc.ClientConfiguration `protobuf:"bytes,2,opt,name=execution_client,json=executionClient,proto3" json:"execution_client,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetcherConfiguration_RemoteExecutionFetcherConfiguration) Reset() {
	*x = FetcherConfiguration_RemoteExecutionFetcherConfiguration{}
	mi := &file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetcherConfiguration_RemoteExecutionFetcherConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetcherConfiguration_RemoteExecutionFetcherConfiguration) ProtoMessage() {}

func (x *FetcherConfiguration_RemoteExecutionFetcherConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetcherConfiguration_RemoteExecutionFetcherConfiguration.ProtoReflect.Descriptor instead.
func (*FetcherConfiguration_RemoteExecutionFetcherConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDescGZIP(), []int{0, 1}
}

func (x *FetcherConfiguration_RemoteExecutionFetcherConfiguration) GetExecutionClient() *grpc.ClientConfiguration {
	if x != nil {
		return x.ExecutionClient
	}
	return nil
}

var File_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDesc = "" +
	"\n" +
	"`github.com/buildbarn/bb-remote-asset/pkg/proto/configuration/bb_remote_asset/fetch/fetcher.proto\x12-buildbarn.configuration.bb_remote_asset.fetch\x1a\x17google/rpc/status.proto\x1aGgithub.com/buildbarn/bb-storage/pkg/proto/configuration/grpc/grpc.proto\x1aPgithub.com/buildbarn/bb-storage/pkg/proto/configuration/http/client/client.proto\"\xd8\x04\n" +
	"\x14FetcherConfiguration\x12r\n" +
	"\x04http\x18\x02 \x01(\v2\\.buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration.HttpFetcherConfigurationH\x00R\x04http\x12*\n" +
	"\x05error\x18\x03 \x01(\v2\x12.google.rpc.StatusH\x00R\x05error\x12\x94\x01\n" +
	"\x10remote_execution\x18\x04 \x01(\v2g.buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration.RemoteExecutionFetcherConfigurationH\x00R\x0fremoteExecution\x1ar\n" +
	"\x18HttpFetcherConfiguration\x12J\n" +
	"\x06client\x18\x03 \x01(\v22.buildbarn.configuration.http.client.ConfigurationR\x06clientJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\x1a\x83\x01\n" +
	"#RemoteExecutionFetcherConfiguration\x12\\\n" +
	"\x10execution_client\x18\x02 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\x0fexecutionClientB\t\n" +
	"\abackendJ\x04\b\x01\x10\x02BTZRgithub.com/buildbarn/bb-remote-asset/pkg/proto/configuration/bb_remote_asset/fetchb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_goTypes = []any{
	(*FetcherConfiguration)(nil),                                     // 0: buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration
	(*FetcherConfiguration_HttpFetcherConfiguration)(nil),            // 1: buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration.HttpFetcherConfiguration
	(*FetcherConfiguration_RemoteExecutionFetcherConfiguration)(nil), // 2: buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration.RemoteExecutionFetcherConfiguration
	(*status.Status)(nil),                                            // 3: google.rpc.Status
	(*client.Configuration)(nil),                                     // 4: buildbarn.configuration.http.client.Configuration
	(*grpc.ClientConfiguration)(nil),                                 // 5: buildbarn.configuration.grpc.ClientConfiguration
}
var file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration.http:type_name -> buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration.HttpFetcherConfiguration
	3, // 1: buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration.error:type_name -> google.rpc.Status
	2, // 2: buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration.remote_execution:type_name -> buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration.RemoteExecutionFetcherConfiguration
	4, // 3: buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration.HttpFetcherConfiguration.client:type_name -> buildbarn.configuration.http.client.Configuration
	5, // 4: buildbarn.configuration.bb_remote_asset.fetch.FetcherConfiguration.RemoteExecutionFetcherConfiguration.execution_client:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_init()
}
func file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_init() {
	if File_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto != nil {
		return
	}
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_msgTypes[0].OneofWrappers = []any{
		(*FetcherConfiguration_Http)(nil),
		(*FetcherConfiguration_Error)(nil),
		(*FetcherConfiguration_RemoteExecution)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto = out.File
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_asset_pkg_proto_configuration_bb_remote_asset_fetch_fetcher_proto_depIdxs = nil
}
